import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Breadcrumbs from "@/components/common/layout/breadcrumbs";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";
import Nav from "@/components/common/layout/header/nav";
import Footer from "@/components/common/layout/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { footerData } from "@/lib/mocks/layout-mocks";
import Script from "next/script";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script
        type="text/javascript"
        src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&libraries=places`}
      />
      <body className={inter.className}>
        {/* <Breadcrumbs
          homeElement="Home"
          separator={<span className="text-coral">&gt;</span>}
          containerClasses="flex m-0 p-0"
          listClasses="hover:underline mx-2 font-bold list-none"
          activeClasses="text-steelblue"
          capitalizeLinks={true}
          linkClass="text-xs hover:underline no-underline text-coral"
        /> */}
        <SessionProvider>
          <Nav className="absolute w-full" />
          {children}
          <Toaster />
          <Footer
            contact={footerData.contact}
            sections={footerData.sections}
            footerLinks={footerData.footerLinks}
          />
        </SessionProvider>
      </body>
    </html>
  );
}
