import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Breadcrumbs from "@/components/common/layout/breadcrumbs";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css"
        />
      </head>
      <body className={inter.className}>
        <Breadcrumbs
          homeElement="Home"
          separator={<span className="text-coral">&gt;</span>}
          containerClasses="flex m-0 p-0"
          listClasses="hover:underline mx-2 font-bold list-none"
          activeClasses="text-steelblue"
          capitalizeLinks={true}
          linkClass="text-xs hover:underline no-underline text-coral"
        />
        <SessionProvider>{children}</SessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
