"use client";
import React, { Suspense } from "react";
import { useMediaQuery } from "react-responsive";

import AllPropertiesMobile from "@/components/dashboard/properties/mobile/all-properties-mobile";
import PropertyListingTable from "@/components/dashboard/properties/tablet-desktop-table/property-listing-table";
import BlockLoader from "@/components/common/animations/block-loader";

const properties = [
  {
    id: 1,
    name: "Colonial Brooklyn",
    price: 1121.01,
    location: "6391 Elgin St. Celina, Delaware 10299",
    bedroom: 2,
    bathroom: 1,
    area: "300 sqm²",
    daysListed: "Jul 7, 2024",
    houseType: "Apartment",
    listingAgent: "Savannah Nguyen",
    isPublic: true,
  },
  {
    id: 2,
    name: "Dreamweaver Mountain Ridge",
    price: 4653.25,
    location: "2118 Thornridge Cir. Syracuse, Connecticut 35624",
    bedroom: 8,
    bathroom: 5,
    area: "1000 sqm²",
    daysListed: "Jul 7, 2024",
    houseType: "Condo",
    listingAgent: "Jane Cooper",
    isPublic: false,
  },
  {
    id: 1,
    name: "Colonial Brooklyn",
    price: 1121.01,
    location: "6391 Elgin St. Celina, Delaware 10299",
    bedroom: 2,
    bathroom: 1,
    area: "300 sqm²",
    daysListed: "Jul 7, 2024",
    houseType: "Apartment",
    listingAgent: "Savannah Nguyen",
    isPublic: true,
  },
  {
    id: 2,
    name: "Dreamweaver Mountain Ridge",
    price: 4653.25,
    location: "2118 Thornridge Cir. Syracuse, Connecticut 35624",
    bedroom: 8,
    bathroom: 5,
    area: "1000 sqm²",
    daysListed: "Jul 7, 2024",
    houseType: "Condo",
    listingAgent: "Jane Cooper",
    isPublic: false,
  },
  {
    id: 1,
    name: "Colonial Brooklyn",
    price: 1121.01,
    location: "6391 Elgin St. Celina, Delaware 10299",
    bedroom: 2,
    bathroom: 1,
    area: "300 sqm²",
    daysListed: "Jul 7, 2024",
    houseType: "Apartment",
    listingAgent: "Savannah Nguyen",
    isPublic: true,
  },
  {
    id: 2,
    name: "Dreamweaver Mountain Ridge",
    price: 4653.25,
    location: "2118 Thornridge Cir. Syracuse, Connecticut 35624",
    bedroom: 8,
    bathroom: 5,
    area: "1000 sqm²",
    daysListed: "Jul 7, 2024",
    houseType: "Condo",
    listingAgent: "Jane Cooper",
    isPublic: false,
  },
  {
    id: 1,
    name: "Colonial Brooklyn",
    price: 1121.01,
    location: "6391 Elgin St. Celina, Delaware 10299",
    bedroom: 2,
    bathroom: 1,
    area: "300 sqm²",
    daysListed: "Jul 7, 2024",
    houseType: "Apartment",
    listingAgent: "Savannah Nguyen",
    isPublic: true,
  },
  {
    id: 2,
    name: "Dreamweaver Mountain Ridge",
    price: 4653.25,
    location: "2118 Thornridge Cir. Syracuse, Connecticut 35624",
    bedroom: 8,
    bathroom: 5,
    area: "1000 sqm²",
    daysListed: "Jul 7, 2024",
    houseType: "Condo",
    listingAgent: "Jane Cooper",
    isPublic: false,
  },
  {
    id: 1,
    name: "Colonial Brooklyn",
    price: 1121.01,
    location: "6391 Elgin St. Celina, Delaware 10299",
    bedroom: 2,
    bathroom: 1,
    area: "300 sqm²",
    daysListed: "Jul 7, 2024",
    houseType: "Apartment",
    listingAgent: "Savannah Nguyen",
    isPublic: true,
  },
  {
    id: 2,
    name: "Dreamweaver Mountain Ridge",
    price: 4653.25,
    location: "2118 Thornridge Cir. Syracuse, Connecticut 35624",
    bedroom: 8,
    bathroom: 5,
    area: "1000 sqm²",
    daysListed: "Jul 7, 2024",
    houseType: "Condo",
    listingAgent: "Jane Cooper",
    isPublic: false,
  },
  {
    id: 1,
    name: "Colonial Brooklyn",
    price: 1121.01,
    location: "6391 Elgin St. Celina, Delaware 10299",
    bedroom: 2,
    bathroom: 1,
    area: "300 sqm²",
    daysListed: "Jul 7, 2024",
    houseType: "Apartment",
    listingAgent: "Savannah Nguyen",
    isPublic: true,
  },
  {
    id: 2,
    name: "Dreamweaver Mountain Ridge",
    price: 4653.25,
    location: "2118 Thornridge Cir. Syracuse, Connecticut 35624",
    bedroom: 8,
    bathroom: 5,
    area: "1000 sqm²",
    daysListed: "Jul 7, 2024",
    houseType: "Condo",
    listingAgent: "Jane Cooper",
    isPublic: false,
  },
  {
    id: 1,
    name: "Colonial Brooklyn",
    price: 1121.01,
    location: "6391 Elgin St. Celina, Delaware 10299",
    bedroom: 2,
    bathroom: 1,
    area: "300 sqm²",
    daysListed: "Jul 7, 2024",
    houseType: "Apartment",
    listingAgent: "Savannah Nguyen",
    isPublic: true,
  },
  {
    id: 2,
    name: "Dreamweaver Mountain Ridge",
    price: 4653.25,
    location: "2118 Thornridge Cir. Syracuse, Connecticut 35624",
    bedroom: 8,
    bathroom: 5,
    area: "1000 sqm²",
    daysListed: "Jul 7, 2024",
    houseType: "Condo",
    listingAgent: "Jane Cooper",
    isPublic: false,
  },
  // ... (include all other properties here)
];

export default function DashboardPropertyList() {
  const isTabletOrDesktop = useMediaQuery({ minWidth: 768 });

  return (
    <Suspense fallback={<BlockLoader message="Loading properties..." />}>
      {isTabletOrDesktop ? (
        <PropertyListingTable properties={properties} />
      ) : (
        <AllPropertiesMobile />
      )}
    </Suspense>
  );
}
