import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Breadcrumbs from "@/components/common/layout/breadcrumbs";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";
import Nav from "@/components/common/layout/header/nav";
import Footer from "@/components/common/layout/footer";
import DashboardSideBar from "@/components/dashboard/navs/dashboard-sidebar";
import DashboardHeader from "@/components/dashboard/dashboard-header";
import QuickActionToolbar from "@/components/dashboard/navs/quick-action-toolbar";
import DashboardSearch from "@/components/dashboard/dashboard-search";
import DashboardNav from "@/components/dashboard/navs/dashboard-nav";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script
        type="text/javascript"
        src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&libraries=places`}
      />
      <body className={inter.className}>
        <SessionProvider>
          <div className="flex h-screen bg-dash-background font-dash-sans">
            <DashboardSideBar />

            <div className="flex flex-1 flex-col overflow-hidden">
              <DashboardHeader agentName="Alexandar Simmons" />

              <main className="flex-1 overflow-y-auto p-4">
                <div className="space-y-4">
                  <QuickActionToolbar />

                  <DashboardSearch />

                  {children}
                </div>
              </main>
              <DashboardNav />
            </div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
