import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Breadcrumbs from "@/components/common/layout/breadcrumbs";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";
import Nav from "@/components/common/layout/header/nav";
import Footer from "@/components/common/layout/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic&display=optional"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.4.1/milligram.css"
        />
      </head>
      <body>
        <Breadcrumbs
          homeElement="Home"
          separator={<span className="text-coral">&gt;</span>}
          containerClasses="flex m-0 p-0 mt-[6rem]"
          listClasses="hover:underline mx-2 font-bold list-none"
          activeClasses="text-steelblue"
          capitalizeLinks={true}
          linkClass="text-xs hover:underline no-underline text-coral"
        />
        <SessionProvider>
          <main>{children}</main>
        </SessionProvider>
      </body>
      {/*
       <html lang="en">
      <body className={inter.className}>
        <Nav />

        <SessionProvider>{children}</SessionProvider>
        <Toaster />
        <Footer />
      </body>

      </html>
      */}
    </html>
  );
}
